### PR TITLE
Repo clean | Add more br packages

### PR DESCRIPTION
**Pull request by abejgonzalez**
Fixes `.gitignore` files to properly ignore generated files. Also, adds `memcached zeromq zmqpp cppzmq` needed for FireSim paper results to be generated (https://github.com/firesim/mutilate-loadgen-riscv-release). I don't know what `BR2_COMPILER_PARANOID_UNSAFE_PATH=y` is, maybe we should unset?

### CODE REVIEW

**Comment by abejgonzalez** [comment]
@jz this at least builds in FireSim. this should be good for review.

**Comment by abejgonzalez** [comment]
According to this (below) the extra BR config throws an error if things are misconfigured (which I think is probably good): https://github.com/rancher/buildroot/blob/881dae3a9c086ee3880834e10f72baea221f4945/Config.in#L662

**Review by tianrui-wei — COMMENTED** [review]
I noticed you're generating these configuration changes with a different buildroot version. Can you include the buildroot bump in your PR as well?

**Review by jerryz123 — APPROVED** [review]

**Comment by abejgonzalez** [comment]
> I noticed you're generating these configuration changes with a different buildroot version. Can you include the buildroot bump in your PR as well?

I used the `buildroot` version that was in FireMarshal main. I'll double check again.

**Comment by jerryz123** [comment]
Actually good catch @tianrui-wei ... abe can you regen those with the current BR

**Comment by jerryz123** [comment]
Ah you are right Abe, I didn't do the right thing when I bumped buildroot.

**Pull request merged**
