### PR TITLE
Use FireSim sudo scripts if available

### PR DESCRIPTION
**Pull request by abejgonzalez**
Try to use FireSim's `sudo` scripts when available (instead of defaulting to `guestmount` or using `cpio` with `sudo`).

### CODE REVIEW

**Review by jerryz123 — APPROVED** [review]
This global stuff is ugly... but I don't think I can think of another solution quickly.

**Comment by abejgonzalez** [comment]
I'm unsure why the `fed-smoke0` test doesn't work (it runs locally) and all other tests pass. This should be good to merge.

**Comment by jerryz123** [comment]
Does the CI have the same sudo settings as your machine? I see:
```
2024-06-17T22:07:36.2258753Z 2024-06-17 15:05:55,794 [run         ] [DEBUG]  DEBUG: cp: cannot create regular file '/scratch/buildbot/firemarshal-ci-shared/firemarshal-a21bc92476b0e8375efbee3bdc86ee567e97de48/disk-mount/etc/shadow': Permission denied
``` 
This feels like a related failure

**Review by jerryz123 — DISMISSED** [review]
I didn't realize the tests had been broken... if you judge the CI failures to be unrelated go ahead and merge

**Comment by abejgonzalez** [comment]
Copying to/from the mountpoint is now more complicated. Now it recursively `chmod`'s all directories in the mountpoint s.t. it can safely copy in/out files (these `chmod`'s are reverted afterwards to keep the same permissions on the directories). This works around an issue where `marshal build`'s `mount` would leave a sub-dir in the mountpoint with incorrect permissions while running a separate `subprocess.run(... mount ...)` (virtually the same way FireMarshal does the mount) has the proper permissions on the sub-dir.

**Review by jerryz123 — APPROVED** [review]
Thanks for dealing with this

**Pull request merged**
